### ISSUE TITLE
Add multi-cpu architecture build

### ISSUE THREAD

**Issue by ggallard** [Identicum/oauth-demoapi-spring-jwt#1]
https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-3-building-in-github-action-ci-a382feab5af9

**Comment by debora2004** [comment]
Fixed with https://github.com/Identicum/oauth-demoapi-spring-jwt/commit/757dbd353d28f9b78fd009229c7be9385c63ab77
